class IconKeywords {
  static const Map<String, List<String>> keywords = {
    // Actions & Navigation
    'check': ['tick', 'done', 'complete', 'success', 'finish', 'ok', 'yes'],
    'close': ['cancel', 'remove', 'x', 'cross', 'stop', 'exit', 'no'],
    'add': ['plus', 'create', 'new', 'more', 'insert', 'append'],
    'delete': ['trash', 'bin', 'remove', 'discard', 'junk', 'rubbish', 'erase', 'clear'],
    'edit': ['pencil', 'change', 'modify', 'update', 'write', 'draw', 'pen'],
    'home': ['house', 'residence', 'building', 'place', 'main', 'start'],
    'search': ['find', 'look', 'magnify', 'query', 'explore', 'seek'],
    'settings': ['gear', 'cog', 'config', 'preferences', 'options', 'control', 'setup'],
    'menu': ['hamburger', 'list', 'options', 'navigation', 'drawer'],
    'arrow_forward': ['right', 'next', 'go', 'direction', 'pointer'],
    'arrow_back': ['left', 'previous', 'return', 'undo', 'direction', 'pointer'],
    'done_all': ['ticks', 'complete', 'finished', 'success', 'multi'],
    'refresh': ['reload', 'sync', 'update', 'renew', 'cycle', 'spin'],
    'sync': ['refresh', 'reload', 'update', 'cycle', 'cloud'],
    'link': ['url', 'web', 'connect', 'chain', 'attach', 'hyperlink'],
    'share': ['send', 'social', 'network', 'broadcast', 'publish'],
    'more_horiz': ['dots', 'options', 'menu', 'overflow'],
    'more_vert': ['dots', 'options', 'menu', 'overflow'],

    // Time & Date
    'event': ['calendar', 'date', 'appointment', 'meeting', 'schedule', 'plan'],
    'schedule': ['clock', 'time', 'watch', 'calendar', 'plan', 'timeline'],
    'timer': ['countdown', 'stopwatch', 'clock', 'duration', 'sand'],
    'alarm': ['wake', 'clock', 'alert', 'notification', 'ring', 'morning'],
    'access_time': ['clock', 'watch', 'now', 'schedule'],
    'calendar_today': ['date', 'day', 'month', 'year', 'schedule', 'event'],
    'update': ['refresh', 'renew', 'sync', 'reload'],
    'history': ['past', 'recent', 'clock', 'back', 'time', 'log'],
    'hourglass_empty': ['wait', 'loading', 'pending', 'time', 'sand'],
    'pending_actions': ['wait', 'todo', 'task', 'list', 'clipboard'],
    'bedtime': ['sleep', 'night', 'moon', 'rest', 'bed'],
    'hourglass_full': ['wait', 'timer', 'sand', 'pending'],

    // Work & Office
    'work': ['job', 'career', 'briefcase', 'office', 'business', 'professional'],
    'business': ['building', 'office', 'company', 'work', 'corporate', 'enterprise'],
    'folder': ['file', 'directory', 'archive', 'organize', 'document'],
    'attach_file': ['paperclip', 'attachment', 'link', 'add', 'document'],
    'description': ['document', 'file', 'paper', 'text', 'article', 'note'],
    'insert_drive_file': ['document', 'file', 'paper', 'data'],
    'assignment': ['clipboard', 'task', 'list', 'todo', 'homework', 'exam'],
    'note': ['paper', 'sticky', 'memo', 'write', 'text'],
    'dashboard': ['analytics', 'overview', 'stats', 'grid', 'cards'],
    'assessment': ['report', 'analytics', 'chart', 'graph', 'data', 'stats'],
    'analytics': ['chart', 'graph', 'data', 'stats', 'trend', 'growth'],
    'pie_chart': ['graph', 'data', 'stats', 'analytics', 'portion'],
    'mail': ['email', 'letter', 'envelope', 'message', 'post', 'inbox'],
    'email': ['mail', 'letter', 'envelope', 'message', 'contact'],
    'send': ['paper plane', 'message', 'deliver', 'submit', 'mail'],
    'inbox': ['tray', 'mail', 'message', 'box', 'receive'],
    'phone': ['call', 'telephone', 'mobile', 'cell', 'contact', 'talk'],
    'contacts': ['people', 'address book', 'directory', 'users', 'friends'],
    'group': ['people', 'team', 'users', 'community', 'social', 'friends'],
    'meeting_room': ['door', 'office', 'room', 'conference', 'enter', 'exit'],
    'print': ['printer', 'paper', 'document', 'copy'],
    'archive': ['box', 'storage', 'save', 'history', 'backup'],
    'unarchive': ['restore', 'unpack', 'retrieve'],
    'computer': ['pc', 'monitor', 'screen', 'desktop', 'device', 'tech'],
    'laptop': ['computer', 'macbook', 'pc', 'device', 'tech', 'work'],
    'keyboard': ['type', 'input', 'computer', 'text'],
    'mouse': ['click', 'pointer', 'computer', 'device'],
    'badge': ['id', 'card', 'work', 'employee', 'pass'],
    'cases': ['briefcase', 'work', 'bag', 'travel'],
    'table_chart': ['data', 'analytics', 'spreadsheet', 'grid'],

    // Education
    'school': ['education', 'university', 'college', 'student', 'learn', 'building', 'graduation'],
    'book': ['read', 'study', 'learn', 'library', 'textbook', 'novel', 'literature'],
    'menu_book': ['open book', 'read', 'study', 'learn'],
    'library_books': ['collection', 'stack', 'read', 'study'],
    'bookmark': ['save', 'favorite', 'tag', 'mark', 'place'],
    'class_': ['book', 'read', 'study', 'learn'], // Icon name is 'class_' but usually looks like a book
    'local_library': ['building', 'study', 'read', 'books', 'school'],
    'import_contacts': ['address book', 'notebook', 'directory'],
    'edit_note': ['write', 'pencil', 'edit', 'document'],
    'calculate': ['math', 'calculator', 'numbers', 'finance', 'add', 'subtract'],
    'science': ['chemistry', 'flask', 'lab', 'experiment', 'biology', 'physics', 'research'],
    'psychology': ['brain', 'mind', 'thought', 'mental', 'health'],
    'lightbulb_circle': ['idea', 'smart', 'think', 'solution'],

    // Health & Fitness
    'fitness_center': ['gym', 'workout', 'exercise', 'weight', 'dumbbell', 'lifting', 'muscle', 'train', 'sport'],
    'directions_run': ['run', 'jog', 'sprint', 'exercise', 'cardio', 'sport', 'person'],
    'directions_walk': ['walk', 'hike', 'stroll', 'exercise', 'pedestrian', 'person'],
    'directions_bike': ['bicycle', 'cycle', 'ride', 'sport', 'exercise', 'transport'],
    'pool': ['swim', 'water', 'swimming', 'sport', 'exercise', 'dive'],
    'sports_soccer': ['football', 'ball', 'game', 'sport', 'match'],
    'sports_basketball': ['ball', 'hoop', 'game', 'sport', 'match'],
    'sports_tennis': ['racket', 'ball', 'game', 'sport', 'match'],
    'sports_volleyball': ['ball', 'game', 'sport', 'match', 'beach'],
    'sports_football': ['american', 'rugby', 'ball', 'game', 'sport'],
    'sports_baseball': ['bat', 'ball', 'game', 'sport'],
    'sports_golf': ['club', 'ball', 'game', 'sport', 'course'],
    'sports_esports': ['game', 'gaming', 'controller', 'console', 'play', 'video'],
    'self_improvement': ['meditation', 'yoga', 'zen', 'mindfulness', 'lotus', 'relax'],
    'spa': ['lotus', 'relax', 'flower', 'wellness', 'massage'],
    'monitor_heart': ['ecg', 'cardio', 'health', 'pulse', 'beat', 'medical'],
    'local_hospital': ['doctor', 'medical', 'health', 'clinic', 'emergency', 'cross', 'ambulance'],
    'local_pharmacy': ['medicine', 'drug', 'pill', 'store', 'medical', 'prescription'],
    'healing': ['bandage', 'bandaid', 'health', 'fix', 'medical', 'wound'],
    'medication': ['pill', 'drug', 'capsule', 'medicine', 'vitamin', 'health'],
    'medical_services': ['bag', 'doctor', 'health', 'kit', 'first aid'],
    'hiking': ['walk', 'trek', 'mountain', 'nature', 'exercise'],
    'downhill_skiing': ['snow', 'winter', 'sport', 'mountain'],
    'kayaking': ['boat', 'water', 'river', 'sport', 'paddle'],
    'skateboarding': ['board', 'skate', 'sport', 'urban'],
    'rowing': ['boat', 'water', 'exercise', 'gym', 'sport'],
    'monitor_weight': ['scale', 'weight', 'health', 'diet'],

    // Food & Dining
    'restaurant': ['fork', 'knife', 'food', 'eat', 'dinner', 'lunch', 'meal', 'cafe'],
    'restaurant_menu': ['list', 'food', 'order', 'book'],
    'local_dining': ['fork', 'spoon', 'food', 'eat', 'meal'],
    'local_cafe': ['coffee', 'tea', 'cup', 'mug', 'drink', 'beverage', 'hot', 'breakfast'],
    'coffee': ['cup', 'mug', 'drink', 'cafe', 'tea', 'morning'],
    'lunch_dining': ['burger', 'food', 'meal', 'eat', 'snack'],
    'dinner_dining': ['bowl', 'food', 'meal', 'eat', 'soup'],
    'breakfast_dining': ['croissant', 'food', 'meal', 'eat', 'morning', 'bread'],
    'fastfood': ['burger', 'drink', 'soda', 'meal', 'junk', 'snack'],
    'cake': ['birthday', 'dessert', 'sweet', 'celebration', 'party'],
    'liquor': ['alcohol', 'drink', 'bottle', 'bar', 'wine', 'spirit'],
    'local_bar': ['cocktail', 'martini', 'drink', 'alcohol', 'wine', 'party'],
    'local_pizza': ['slice', 'food', 'italian', 'fast', 'snack'],
    'bakery_dining': ['croissant', 'bread', 'food', 'breakfast', 'morning'],
    'kitchen': ['fridge', 'refrigerator', 'appliance', 'food', 'cook'],
    'icecream': ['dessert', 'sweet', 'cold', 'summer', 'treat'],
    'takeout_dining': ['bag', 'food', 'fast', 'delivery', 'pickup'],
    'egg': ['breakfast', 'food', 'cooking', 'protein'],
    'soup_kitchen': ['bowl', 'food', 'warm', 'meal'],
    'ramen_dining': ['noodles', 'soup', 'japanese', 'food', 'bowl'],
    'brunch_dining': ['breakfast', 'lunch', 'croissant', 'drink', 'meal'],

    // Shopping & Finance
    'shopping_cart': ['buy', 'store', 'shop', 'groceries', 'market', 'ecommerce'],
    'shopping_bag': ['buy', 'store', 'shop', 'fashion', 'retail'],
    'store': ['shop', 'building', 'market', 'retail', 'business'],
    'local_offer': ['tag', 'price', 'discount', 'sale', 'label', 'deal'],
    'payments': ['money', 'cash', 'card', 'dollar', 'finance', 'pay'],
    'attach_money': ['dollar', 'cash', 'money', 'finance', 'currency', 'cost', 'price'],
    'credit_card': ['pay', 'debit', 'money', 'finance', 'bank'],
    'account_balance': ['bank', 'building', 'finance', 'money', 'government'],
    'account_balance_wallet': ['wallet', 'money', 'cash', 'pay', 'finance'],
    'receipt': ['bill', 'invoice', 'paper', 'payment', 'check'],
    'receipt_long': ['bill', 'invoice', 'paper', 'list', 'history'],
    'savings': ['piggy bank', 'money', 'finance', 'save', 'coin'],
    'euro': ['currency', 'money', 'finance', 'pay', 'cost'],
    'currency_bitcoin': ['crypto', 'money', 'finance', 'digital', 'coin'],
    'diamond': ['gem', 'jewelry', 'expensive', 'luxury', 'stone'],
    'sell': ['tag', 'price', 'shop', 'store', 'discount'],

    // Travel & Transport
    'flight': ['plane', 'airplane', 'fly', 'travel', 'trip', 'airport', 'holiday'],
    'flight_takeoff': ['plane', 'airplane', 'depart', 'fly', 'travel'],
    'flight_land': ['plane', 'airplane', 'arrive', 'fly', 'travel'],
    'train': ['rail', 'subway', 'metro', 'transport', 'commute', 'travel'],
    'directions_car': ['drive', 'vehicle', 'auto', 'taxi', 'uber', 'transport', 'road', 'trip'],
    'directions_bus': ['coach', 'transport', 'commute', 'public', 'vehicle'],
    'directions_boat': ['ship', 'ferry', 'cruise', 'sea', 'water', 'transport'],
    'subway': ['train', 'metro', 'rail', 'underground', 'transport'],
    'tram': ['train', 'transport', 'city'],
    'local_taxi': ['cab', 'car', 'drive', 'service', 'transport'],
    'commute': ['travel', 'work', 'transport', 'train'],
    'map': ['location', 'place', 'guide', 'navigation', 'world'],
    'navigation': ['arrow', 'direction', 'guide', 'gps'],
    'place': ['pin', 'location', 'marker', 'map', 'spot', 'here'],
    'explore': ['compass', 'discover', 'travel', 'map', 'direction'],
    'hotel': ['bed', 'sleep', 'room', 'accommodation', 'holiday', 'travel'],
    'luggage': ['suitcase', 'bag', 'travel', 'trip', 'airport', 'holiday'],
    'local_gas_station': ['fuel', 'pump', 'petrol', 'car', 'transport'],
    'ev_station': ['charge', 'electric', 'power', 'car', 'energy'],
    'two_wheeler': ['motorcycle', 'bike', 'transport', 'vehicle'],
    'pedal_bike': ['bicycle', 'cycle', 'ride', 'sport'],
    'moped': ['scooter', 'bike', 'transport', 'city'],
    'airport_shuttle': ['bus', 'van', 'transport', 'travel', 'airport'],
    'car_rental': ['car', 'key', 'rent', 'transport', 'travel'],

    // Home & Lifestyle
    'king_bed': ['sleep', 'rest', 'hotel', 'bedroom', 'furniture', 'nap'],
    'weekend': ['sofa', 'couch', 'relax', 'lounge', 'furniture', 'chair'],
    'chair': ['seat', 'furniture', 'sit', 'relax'],
    'lightbulb': ['idea', 'lamp', 'energy', 'smart', 'bright', 'electric'],
    'lightbulb_outline': ['idea', 'lamp', 'energy'],
    'power': ['plug', 'socket', 'electric', 'energy', 'charge'],
    'wifi': ['internet', 'network', 'connection', 'wireless', 'signal'],
    'tv': ['television', 'screen', 'movie', 'show', 'watch', 'monitor'],
    'cleaning_services': ['broom', 'sparkle', 'wash', 'clean', 'tidy', 'housework'],
    'local_laundry_service': ['washer', 'machine', 'clean', 'clothes', 'wash'],
    'build': ['wrench', 'tool', 'fix', 'repair', 'construction', 'settings'],
    'handyman': ['tool', 'repair', 'fix', 'bag'],
    'plumbing': ['wrench', 'pipe', 'water', 'fix', 'repair'],
    'pets': ['dog', 'cat', 'paw', 'animal', 'veterinarian'],
    'park': ['tree', 'nature', 'outdoors', 'garden', 'forest'],
    'forest': ['tree', 'nature', 'wood', 'outdoors'],
    'nature': ['tree', 'leaf', 'plant', 'outdoors'],
    'wb_sunny': ['sun', 'weather', 'bright', 'day', 'light'],
    'nightlight': ['moon', 'star', 'sleep', 'dark', 'weather', 'evening'],
    'ac_unit': ['snow', 'cold', 'air', 'weather', 'winter', 'cool'],
    'wb_twilight': ['sunset', 'sunrise', 'sun', 'morning', 'evening'],
    'wb_cloudy': ['cloud', 'weather', 'overcast', 'grey'],
    'water_drop': ['rain', 'water', 'weather', 'wet', 'drop'],
    'umbrella': ['rain', 'weather', 'wet', 'protection'],
    'air': ['wind', 'weather', 'blow', 'breeze'],
    'thermostat': ['temperature', 'heat', 'cold', 'weather', 'control'],
    'yard': ['garden', 'grass', 'nature', 'outdoors', 'home'],
    'living': ['room', 'sofa', 'chair', 'home', 'furniture'],
    'bed': ['sleep', 'rest', 'hotel', 'furniture', 'room'],
    'garage': ['car', 'parking', 'home', 'building'],
    'shower': ['bathroom', 'water', 'wash', 'clean'],

    // Social & Entertainment
    'music_note': ['song', 'audio', 'sound', 'melody', 'listen', 'tune'],
    'music_video': ['clip', 'media', 'play', 'watch'],
    'headphones': ['listen', 'music', 'audio', 'sound', 'headset'],
    'movie': ['film', 'cinema', 'video', 'show', 'watch', 'clapperboard'],
    'theaters': ['screen', 'cinema', 'movie', 'show'],
    'videogame_asset': ['controller', 'gamepad', 'play', 'console', 'esports', 'joystick'],
    'camera_alt': ['photo', 'picture', 'image', 'capture', 'lens', 'snap'],
    'photo': ['image', 'picture', 'gallery'],
    'palette': ['art', 'paint', 'color', 'design', 'draw'],
    'brush': ['paint', 'art', 'draw', 'design', 'tool'],
    'theater_comedy': ['masks', 'drama', 'acting', 'performance'],
    'stadium': ['arena', 'sport', 'event', 'concert'],
    'celebration': ['party', 'confetti', 'fun', 'event', 'holiday'],
    'card_giftcard': ['present', 'box', 'birthday', 'christmas', 'reward'],
    'piano': ['music', 'instrument', 'play', 'keys', 'song'],
    'mic': ['microphone', 'record', 'voice', 'audio', 'sound'],
    'radio': ['music', 'listen', 'broadcast', 'audio', 'sound'],
    'podcasts': ['audio', 'listen', 'talk', 'radio', 'show'],
    'album': ['music', 'record', 'cd', 'vinyl', 'song'],
    'sports_bar': ['drink', 'alcohol', 'beer', 'game', 'pub'],
    'casino': ['gamble', 'game', 'dice', 'card', 'bet'],
    'toys': ['play', 'game', 'child', 'fun', 'block'],

    // Miscellaneous
    'star': ['favorite', 'rate', 'best', 'featured', 'rating'],
    'star_border': ['rate', 'rating', 'favorite'],
    'favorite': ['heart', 'love', 'like', 'health', 'life'],
    'favorite_border': ['heart', 'love', 'like'],
    'thumb_up': ['like', 'approve', 'good', 'yes', 'ok'],
    'warning': ['alert', 'danger', 'caution', 'error', 'stop'],
    'warning_amber': ['alert', 'caution', 'triangle'],
    'error': ['alert', 'stop', 'wrong', 'fail', 'bug'],
    'info': ['help', 'details', 'about'],
    'help': ['question', 'support', 'faq', 'query'],
    'lock': ['secure', 'protect', 'private', 'password', 'key'],
    'visibility': ['eye', 'see', 'view', 'show', 'watch'],
    'visibility_off': ['hide', 'conceal', 'private'],
    'language': ['globe', 'world', 'translate', 'internet'],
    'public': ['globe', 'world', 'earth', 'internet'],
    'face': ['person', 'user', 'profile', 'account', 'human', 'avatar'],
    'fingerprint': ['id', 'auth', 'security', 'touch', 'login'],
    'bolt': ['lightning', 'energy', 'electric', 'power', 'charge', 'fast', 'flash'],
    'auto_awesome': ['stars', 'magic', 'sparkle', 'ai', 'smart', 'enhance'],
    'rocket_launch': ['space', 'fly', 'start', 'launch', 'fast'],
    'whatshot': ['fire', 'flame', 'hot', 'burn', 'trend'],
    'key': ['lock', 'security', 'password', 'access', 'door'],
    'shield': ['protect', 'security', 'guard', 'defense', 'safe'],
    'flag': ['banner', 'country', 'mark', 'goal', 'finish'],
    'push_pin': ['marker', 'location', 'save', 'keep', 'note'],
  };
}
