import 'package:flutter/material.dart';

class AppIcons {
  static const Map<String, IconData> allIcons = {
    // Actions & Navigation
    'check': Icons.check,
    'close': Icons.close,
    'add': Icons.add,
    'delete': Icons.delete,
    'edit': Icons.edit,
    'home': Icons.home,
    'search': Icons.search,
    'settings': Icons.settings,
    'menu': Icons.menu,
    'arrow_forward': Icons.arrow_forward,
    'arrow_back': Icons.arrow_back,
    'done_all': Icons.done_all,
    'refresh': Icons.refresh,
    'sync': Icons.sync,
    'link': Icons.link,
    'share': Icons.share,
    'more_horiz': Icons.more_horiz,
    'more_vert': Icons.more_vert,

    // Time & Date
    'event': Icons.event,
    'schedule': Icons.schedule,
    'timer': Icons.timer,
    'alarm': Icons.alarm,
    'access_time': Icons.access_time,
    'calendar_today': Icons.calendar_today,
    'update': Icons.update,
    'history': Icons.history,
    'hourglass_empty': Icons.hourglass_empty,
    'pending_actions': Icons.pending_actions,

    // Work & Office
    'work': Icons.work,
    'business': Icons.business,
    'folder': Icons.folder,
    'attach_file': Icons.attach_file,
    'description': Icons.description,
    'insert_drive_file': Icons.insert_drive_file,
    'assignment': Icons.assignment,
    'note': Icons.note,
    'dashboard': Icons.dashboard,
    'assessment': Icons.assessment,
    'analytics': Icons.analytics,
    'pie_chart': Icons.pie_chart,
    'mail': Icons.mail,
    'email': Icons.email,
    'send': Icons.send,
    'inbox': Icons.inbox,
    'phone': Icons.phone,
    'contacts': Icons.contacts,
    'group': Icons.group,
    'meeting_room': Icons.meeting_room,
    'print': Icons.print,
    'archive': Icons.archive,
    'unarchive': Icons.unarchive,
    'computer': Icons.computer,
    'laptop': Icons.laptop,
    'keyboard': Icons.keyboard,
    'mouse': Icons.mouse,

    // Education
    'school': Icons.school,
    'book': Icons.book,
    'menu_book': Icons.menu_book,
    'library_books': Icons.library_books,
    'bookmark': Icons.bookmark,
    'class_': Icons.class_,
    'local_library': Icons.local_library,
    'import_contacts': Icons.import_contacts,
    'edit_note': Icons.edit_note,
    'calculate': Icons.calculate,
    'science': Icons.science,

    // Health & Fitness
    'fitness_center': Icons.fitness_center,
    'directions_run': Icons.directions_run,
    'directions_walk': Icons.directions_walk,
    'directions_bike': Icons.directions_bike,
    'pool': Icons.pool,
    'sports_soccer': Icons.sports_soccer,
    'sports_basketball': Icons.sports_basketball,
    'sports_tennis': Icons.sports_tennis,
    'sports_volleyball': Icons.sports_volleyball,
    'sports_football': Icons.sports_football,
    'sports_baseball': Icons.sports_baseball,
    'sports_golf': Icons.sports_golf,
    'sports_esports': Icons.sports_esports,
    'self_improvement': Icons.self_improvement,
    'spa': Icons.spa,
    'monitor_heart': Icons.monitor_heart,
    'local_hospital': Icons.local_hospital,
    'local_pharmacy': Icons.local_pharmacy,
    'healing': Icons.healing,
    'medication': Icons.medication,
    'medical_services': Icons.medical_services,

    // Food & Dining
    'restaurant': Icons.restaurant,
    'restaurant_menu': Icons.restaurant_menu,
    'local_dining': Icons.local_dining,
    'local_cafe': Icons.local_cafe,
    'coffee': Icons.coffee,
    'lunch_dining': Icons.lunch_dining,
    'dinner_dining': Icons.dinner_dining,
    'breakfast_dining': Icons.breakfast_dining,
    'fastfood': Icons.fastfood,
    'cake': Icons.cake,
    'liquor': Icons.liquor,
    'local_bar': Icons.local_bar,
    'local_pizza': Icons.local_pizza,
    'bakery_dining': Icons.bakery_dining,
    'kitchen': Icons.kitchen,

    // Shopping & Finance
    'shopping_cart': Icons.shopping_cart,
    'shopping_bag': Icons.shopping_bag,
    'store': Icons.store,
    'local_offer': Icons.local_offer,
    'payments': Icons.payments,
    'attach_money': Icons.attach_money,
    'credit_card': Icons.credit_card,
    'account_balance': Icons.account_balance,
    'account_balance_wallet': Icons.account_balance_wallet,
    'receipt': Icons.receipt,
    'receipt_long': Icons.receipt_long,
    'savings': Icons.savings,
    'euro': Icons.euro,

    // Travel & Transport
    'flight': Icons.flight,
    'flight_takeoff': Icons.flight_takeoff,
    'flight_land': Icons.flight_land,
    'train': Icons.train,
    'directions_car': Icons.directions_car,
    'directions_bus': Icons.directions_bus,
    'directions_boat': Icons.directions_boat,
    'subway': Icons.subway,
    'tram': Icons.tram,
    'local_taxi': Icons.local_taxi,
    'commute': Icons.commute,
    'map': Icons.map,
    'navigation': Icons.navigation,
    'place': Icons.place,
    'explore': Icons.explore,
    'hotel': Icons.hotel,
    'luggage': Icons.luggage,
    'local_gas_station': Icons.local_gas_station,
    'ev_station': Icons.ev_station,

    // Home & Lifestyle
    'king_bed': Icons.king_bed,
    'weekend': Icons.weekend,
    'chair': Icons.chair,
    'lightbulb': Icons.lightbulb,
    'lightbulb_outline': Icons.lightbulb_outline,
    'power': Icons.power,
    'wifi': Icons.wifi,
    'tv': Icons.tv,
    'cleaning_services': Icons.cleaning_services,
    'local_laundry_service': Icons.local_laundry_service,
    'build': Icons.build,
    'handyman': Icons.handyman,
    'plumbing': Icons.plumbing,
    'pets': Icons.pets,
    'park': Icons.park,
    'forest': Icons.forest,
    'nature': Icons.nature,
    'wb_sunny': Icons.wb_sunny,
    'nightlight': Icons.nightlight,
    'ac_unit': Icons.ac_unit,

    // Social & Entertainment
    'music_note': Icons.music_note,
    'music_video': Icons.music_video,
    'headphones': Icons.headphones,
    'movie': Icons.movie,
    'theaters': Icons.theaters,
    'videogame_asset': Icons.videogame_asset,
    'camera_alt': Icons.camera_alt,
    'photo': Icons.photo,
    'palette': Icons.palette,
    'brush': Icons.brush,
    'theater_comedy': Icons.theater_comedy,
    'stadium': Icons.stadium,
    'celebration': Icons.celebration,
    'card_giftcard': Icons.card_giftcard,

    // Miscellaneous
    'star': Icons.star,
    'star_border': Icons.star_border,
    'favorite': Icons.favorite,
    'favorite_border': Icons.favorite_border,
    'thumb_up': Icons.thumb_up,
    'warning': Icons.warning,
    'warning_amber': Icons.warning_amber_rounded,
    'error': Icons.error,
    'info': Icons.info,
    'help': Icons.help,
    'lock': Icons.lock,
    'visibility': Icons.visibility,
    'visibility_off': Icons.visibility_off,
    'language': Icons.language,
    'public': Icons.public,
    'face': Icons.face,
    'fingerprint': Icons.fingerprint,
    'bolt': Icons.bolt,
    'auto_awesome': Icons.auto_awesome,
  };

  static List<IconData> get iconList => allIcons.values.toList();
}
